<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputGLUXConfirmClose</name>
   <tag></tag>
   <elementGuidId>5f6735c4-1153-4eb6-8075-c3efa2867439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='GLUXConfirmClose'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-button.a-column.a-button-primary.a-button-span4.a-button-focus > span.a-button-inner.a-declarative > #GLUXConfirmClose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ff5c6f6-8c89-471c-b884-d7e0a3890be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>20d5cbab-3e6e-4149-aa64-7c6876e79210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXConfirmClose</value>
      <webElementGuid>f4178fc9-1a4b-4609-9b8b-a158e3ab93ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>GLUXConfirmClose-announce</value>
      <webElementGuid>e953f739-ca5b-4189-98ff-c6836322df10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a169647e-4420-4170-833f-acd1738d9b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-1&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/div[@class=&quot;a-popover-footer&quot;]/span[@class=&quot;a-button a-column a-button-primary a-button-span4 a-button-focus&quot;]/span[@class=&quot;a-button-inner a-declarative&quot;]/input[@id=&quot;GLUXConfirmClose&quot;]</value>
      <webElementGuid>2a193203-83dc-48b3-9bcd-77bf764001d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='GLUXConfirmClose'])[2]</value>
      <webElementGuid>048139d7-33d6-4f60-b9b6-898e7277fc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/div[2]/span/span/input</value>
      <webElementGuid>06bdc148-7654-401f-9bc7-303f2ef82795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/input</value>
      <webElementGuid>85031037-b39e-42e7-a09a-d100414900d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GLUXConfirmClose' and @type = 'submit']</value>
      <webElementGuid>2bddcc62-e1d9-4f53-aea8-30d45f4e27b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
