<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hello, sign in</name>
   <tag></tag>
   <elementGuidId>78875c39-fc5c-4583-a827-799791f99d52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-accountList-nav-line-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aee9d7fa-a694-41f7-9b88-e3063136fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-accountList-nav-line-1</value>
      <webElementGuid>391d30eb-6009-45bd-bcb2-cf8be9de540e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-1 nav-progressive-content</value>
      <webElementGuid>149cd496-c7b5-4b17-8470-fe7fd63330cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello, sign in</value>
      <webElementGuid>15804c12-fb9d-457f-8357-eab548c8d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList-nav-line-1&quot;)</value>
      <webElementGuid>1aaa9529-6091-4ca9-8cd9-014df6299e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='nav-link-accountList-nav-line-1']</value>
      <webElementGuid>4992b1be-3a77-48f2-91d3-37cd1036230b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-link-accountList']/div/span</value>
      <webElementGuid>76c94a04-77f3-445e-b022-5347fbcbe547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>01916e2c-4463-43d8-b6a8-7fc556bf033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'nav-link-accountList-nav-line-1' and (text() = 'Hello, sign in' or . = 'Hello, sign in')]</value>
      <webElementGuid>68862e27-e45b-4223-ba8a-12070775fa3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
