<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnav-search-submit-button</name>
   <tag></tag>
   <elementGuidId>870b521e-be7c-4cae-b71c-1389a356802c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-search-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd986683-7dcc-4ad1-a3d1-bb3ae231bf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-submit-button</value>
      <webElementGuid>9573815d-55bd-463c-8d9d-603367537ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>45ea4339-51d5-4bf7-aaeb-a85bbd1385af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>62d032b1-f609-42aa-b5a5-f83e249f5bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>61806539-24ab-49f9-8d21-0318b78cd173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6edc00bf-d1f6-410c-bef9-88966bef6f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-submit-button&quot;)</value>
      <webElementGuid>a5c2c42f-1286-4a6d-8861-28e009c4cf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-submit-button']</value>
      <webElementGuid>137d8f7b-e8b9-4b3a-a6bf-864c151cf01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nav-search-submit-text']/input</value>
      <webElementGuid>c90c4bf4-37e2-46c1-98e2-c482ec367c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>57be9432-ea63-4d1d-96de-7778d9db86e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nav-search-submit-button' and @type = 'submit']</value>
      <webElementGuid>ea7506cc-9e73-420b-9871-916cc07acaec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
