<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Todays Deals</name>
   <tag></tag>
   <elementGuidId>62bf6b90-6761-47ff-b6db-fd10fdd743af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a222126-ffd1-480d-966a-049848306b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/deals?ref_=nav_cs_gb</value>
      <webElementGuid>3fec90e3-070b-445b-81d4-eda313e1e3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>c6fb35fc-3d86-44f9-8470-e19074a86aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9388202b-c431-4a35-a532-8c6733a24667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>fb3648dd-4461-40a2-b57a-ea199db17938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_2</value>
      <webElementGuid>445de6a2-9cc3-41a4-aa9a-66c126ff2024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_gb</value>
      <webElementGuid>2fdcc33b-683a-488d-9cc8-147ffa219140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>7ni88h-99meek-fv9dyy-hfmp8u</value>
      <webElementGuid>d69130b0-5517-479c-ba16-f18ecbae4c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today's Deals</value>
      <webElementGuid>4e09d04f-30cd-46cf-b61f-970c941b680c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>2bae65a9-ee8a-4114-bd29-4f8060cea071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[3]</value>
      <webElementGuid>ef6afc01-65bd-4aee-9777-1f29142d6b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/deals?ref_=nav_cs_gb')]</value>
      <webElementGuid>a51b739c-8ed1-408d-b064-dd2b6cb4ba9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a[3]</value>
      <webElementGuid>e0e7cc1b-374a-42a7-ae4f-aac8d07d9429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/deals?ref_=nav_cs_gb' and (text() = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;) or . = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Deals&quot;))]</value>
      <webElementGuid>f0be6cb3-da53-4058-911e-fc84eba8570c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
