<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsignInSubmit</name>
   <tag></tag>
   <elementGuidId>2a208f3c-6f24-4e71-98d7-223baf05e672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d202cb89-c09f-490b-8aa0-67e64d31d79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInSubmit</value>
      <webElementGuid>34f43f61-8c67-48bc-9f09-9ae9bcea4614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f5a27f71-ab06-453c-873f-53e2a0f21115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>0921fbf6-1999-4376-891b-71e00ba14a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b74b378e-09fe-44ee-a2e7-785e796f61a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>auth-signin-button-announce</value>
      <webElementGuid>78e76fa1-b449-43f5-a344-138962f4487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInSubmit&quot;)</value>
      <webElementGuid>c31894af-9efd-43f9-97cb-4d5b6c323684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInSubmit']</value>
      <webElementGuid>c0181d6e-18a1-48e8-8967-b15d1867343e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']/span/input</value>
      <webElementGuid>e8121d6a-7ad3-4b12-bc56-7bfec8049295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>8abc6703-84c3-4e9e-86e1-24141b40e880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInSubmit' and @type = 'submit']</value>
      <webElementGuid>5aff16ca-8331-4a87-9f36-6311d834d91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
